services:
  backend:
    image: ghcr.io/promi4s/ocelescope-backend:latest
    volumes:
      - plugins_store:/plugins
    restart: unless-stopped
  frontend:
    image: ghcr.io/promi4s/ocelescope-frontend:latest
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  plugins_store:
